#!/bin/sh

if [ ! -x  /usr/libexec/PlistBuddy ]; then exit 1 ; fi
if [ `whoami` != root ]; then
    echo "Use sudo $0 ESS-ID-NAME"
    exit 0
fi

ESSID="$1"
if [ ${ESSID}X = X ]; then
    echo "Use sudo $0 ESS-ID-NAME"
    exit 1
fi

n=0
ESSID_HEX=""
for i in `/bin/echo -n "$ESSID" | od -t x1 | awk '$1 = " " {print}'` 
do
    ESSID_HEX="${ESSID_HEX}${i}"
    if [ $n -eq 3 ]; then
        ESSID_HEX="${ESSID_HEX}\ "
        n=0
    else
        n=`expr $n + 1`
    fi    
done

# This is for TEST.
if [ "$2"X = X ]; then
    PLIST='/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist'
else
    PLIST="$2"
fi
if [ ! -f "$PLIST" ]; then
    echo "Not found: $PLIST"
    exit 1
fi

IsSystemMode=`/usr/libexec/PlistBuddy -c "print KnownNetworks:wifi.ssid.<$ESSID_HEX>:SystemMode" "$PLIST"`
if [ $? -ne 0 ]; then 
    echo "Error with /usr/libexec/PlistBuddy."
    exit 1 
fi
if [ $IsSystemMode = false ]; then
    /usr/libexec/PlistBuddy -c "set KnownNetworks:wifi.ssid.<$ESSID_HEX>:SystemMode true" "$PLIST"
fi
