#!/bin/sh

NewSystemMode="true"
PLIST='/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist'

myhelp(){
    cat << __HELP

Usage: sudo $0 -w Wireless-Network-Name [-f] [-p /path/to/`basename $PLIST`]

Options:
    -f  : Set SystemMode false (Optional). Default set it true.
    -h  : Show this message.
    -p s: path to the plist file (For debug purpose)
    -w s: SSID aka Wireless network name

__HELP
}

OSVER=`sw_vers -productVersion | awk -F. '{print $2}'`
if [ $OSVER -lt 10 ]; then
    echo "I work only on version 10.10 or later of OS X."
    exit 1
fi

while getopts fhp:w: OPT
do
    case $OPT in
        "f") NewSystemMode="false" ;;
        "p") PLIST="${OPTARG}"     ;;
        "w") ESSID="${OPTARG}"     ;;
        :|\?|"h") SHOWHELP="YES"   ;;
    esac
done

if [ ${ESSID}X = X ]; then myhelp ; exit 1 ; fi
if [ `whoami` != root ]; then myhelp ; exit 1 ; fi
if [ ! -f "$PLIST" ]; then
    echo "Not found: $PLIST"
    myhelp; exit 1
fi

n=0
ESSID_HEX=""
for i in `/bin/echo -n "$ESSID" | od -t x1 | awk '$1 = " " {print}'`
do
    ESSID_HEX="${ESSID_HEX}${i}"
    if [ $n -eq 3 ]; then
        ESSID_HEX="${ESSID_HEX}\ "
        n=0
    else
        n=`expr $n + 1`
    fi
done

CurrentSystemMode=`/usr/libexec/PlistBuddy -c "print KnownNetworks:wifi.ssid.<$ESSID_HEX>:SystemMode" "$PLIST"`
RESULT=$?
if [ $RESULT -ne 0 ]; then exit $RESULT ; fi
if [ $CurrentSystemMode != $NewSystemMode ]; then
    /usr/libexec/PlistBuddy -c "set KnownNetworks:wifi.ssid.<$ESSID_HEX>:SystemMode $NewSystemMode" "$PLIST"
fi
