#!/bin/sh

NewSystemMode="true"
PLIST='/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist'

myhelp(){
    cat __HELP

Usage: sudo $0 -w Wireless-Network-Name [-f] [-p]

Options:
    -f  : Set SystemMode false (Optional)
    -h  : Show this message.
    -p s: the plist file (For debug purpose)
    -w s: SSID aka Wireless network name

__HELP
}

while getopts fhp:w: OPT
do
    case $OPT in
        "f") NewSystemMode="false" ;;
        "p") PLIST="${OPTARG}"     ;;
        "w") ESSID="${OPTARG}"     ;;
        :|\?|"h") SHOWHELP="YES"   ;;
    esac
done

if [ ${ESSID}X = X ]; then myhelp ; exit 1 ; fi
if [ `whoami` != root ]; then myhelp ; exit 1 ; fi
if [ ! -f "$PLIST" ]; then
    echo "Not found: $PLIST"
    myhelp; exit 1
fi

n=0
ESSID_HEX=""
for i in `/bin/echo -n "$ESSID" | od -t x1 | awk '$1 = " " {print}'`
do
    ESSID_HEX="${ESSID_HEX}${i}"
    if [ $n -eq 3 ]; then
        ESSID_HEX="${ESSID_HEX}\ "
        n=0
    else
        n=`expr $n + 1`
    fi
done

CurrentSystemMode=`/usr/libexec/PlistBuddy -c "print KnownNetworks:wifi.ssid.<$ESSID_HEX>:SystemMode" "$PLIST"`
if [ $? -ne 0 ]; then
    echo "Error with /usr/libexec/PlistBuddy."
    exit 1
fi
if [ $IsSystemMode != $NewSystemMode ]; then
    /usr/libexec/PlistBuddy -c "set KnownNetworks:wifi.ssid.<$ESSID_HEX>:SystemMode $NewSystemMode" "$PLIST"
fi
